@startuml
class Compra {
    + Compra()
    + Compra(fechaCompra:DateTime, precioTotal:decimal, usuarioId:string, metodoPagoId:int, codigoDescuento:string?)
    + Id : int <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + UsuarioId : string <<get>> <<set>>
    + MetodoPagoId : int <<get>> <<set>>
    + CodigoDescuento : string? <<get>> <<set>>
}
class "List`1"<T> {
}
Compra --> "FechaCompra" DateTime
Compra --> "Usuario" ApplicationUser
Compra --> "MetodosPago<MetodoPago>" "List`1"
Compra --> "CompraItems<CompraItem>" "IList`1"
@enduml
