@startuml
hide methods
!include Subasta.puml
!include SubastaItem.puml
!include Editorial.puml
!include Libro.puml
!include Visa.puml
!include GooglePay.puml
!include PayPal.puml
!include ApplicationUser.puml
!include MetodoPago.puml
@enduml