@startuml
class Editorial {
    + Editorial()
    + Editorial(id:int, nombre:int)
    + Id : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
}
class "List`1"<T> {
}
Editorial --> "Libros<Libro>" "List`1"
@enduml
