@startuml
!include .\\ApplicationUser.puml
!include .\\Compra.puml
!include .\\CompraItem.puml
!include .\\Genero.puml
!include .\\Libro.puml
!include .\\MetodoPago.puml
!include .\\Reposicion.puml
!include .\\ReposicionItem.puml
!include .\\Subasta.puml
!include .\\SubastaItem.puml
!include .\\Visa.puml
@enduml
