@startuml
class Reposicion {
    + Id : int <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + Comentario : string? <<get>> <<set>>
    + FechaReposicion : DateTime <<get>> <<set>>
}
@enduml
