@startuml
class Reposicion {
    + Id : int <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + Comentario : string? <<get>> <<set>>
    + Reposicion()
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
}
Reposicion --> "FechaReposicion" DateTime
@enduml
